---
- name: Remove Infra for a 3 node cluster
  hosts: localhost
  connection: local
  become: true
  become_method: sudo

  roles:
    - remove_socket_vmnet
    - create_bootp
    - remove_fake_dns_k8s